# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "To build and run unit tests"
  lane :build_run_unit_tests do
    run_tests(workspace: "CoWorkMobileApp.xcworkspace",
            devices: ["iPhone 14 Pro"],
            scheme: "CoWorkMobileApp",
            only_testing: "CoWorkMobileAppTests")
  end

desc "Create ipa"
  lane :build do
    enable_automatic_code_signing
    increment_build_number
    gym
  end

  desc "Upload to App Store"
  lane :upload do
    deliver
  end

desc "Build and run unit tests, create spa, upload to App Store"
	lane :do_everything do
		build_run_unit_tests
		build
		upload
end
end
